### ISSUE TITLE
This image and repository can probably be deleted?

### ISSUE THREAD

**Issue by itsdalmo** [telia-oss/four-o-four#3]
AWS recently introduced `fixed-response` and `redirect` rules for their listeners:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html

In terraform we can use `default_action` when defining the listener (which we then add rules to):
```hcl
  default_action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      message_body = "Fixed response content"
      status_code = "200"
    }
  }
```

This means it's probably safe to delete this repository and the generated docker file, as long as we make sure to update the examples here:
https://github.com/telia-oss/terraform-aws-ecs/blob/master/examples/default/example.tf#L77-L119

**Comment by itsdalmo** [comment]
Sorry, did not mean to assign you @mikael-lindstrom 😂  Just wondered if you had any input

**Comment by mikael-lindstrom** [comment]
Agreed this can now be removed 👍

**Comment by itsdalmo** [comment]
Deleting this repo.
